// AUTO-GENERATED by Dividend_DataStructure/scripts/generate-sync-contract.mjs — DO NOT EDIT.
import type { WatchlistStock } from '../types'

export const H5_SYNC_CONTRACT_HASH = '2f0b9379e85d26de'
export const H5_SYNC_SCHEMA_VERSION = 2
export const SHARED_ACCOUNT_FIELDS = [
  "name",
  "watchlist",
  "feeConfig",
  "cashBalance",
  "cashOpeningBalance",
  "cashTrackingEnabled",
  "cashFundingRecorded",
  "cashFundingCurrencies",
  "cashCalibrations"
] as const
export const MERGED_OBJECT_FIELDS = [
  "feeConfig",
  "cashBalance",
  "cashOpeningBalance",
  "cashFundingCurrencies"
] as const
export const SHARED_STOCK_FIELDS = [
  "code",
  "name",
  "sector",
  "price",
  "dividendPerShare",
  "yieldRate",
  "confirmed",
  "targetYield",
  "targetPrice",
  "price2026",
  "change2026",
  "isHK",
  "isUS",
  "isETF",
  "isFund",
  "isManual",
  "cashCurrency",
  "priceCny",
  "priceLabel",
  "pctChg",
  "shares",
  "costPrice",
  "taxType",
  "marketCap",
  "transactions",
  "dividendManual"
] as const
export const SECTOR_ALIASES = {
  "美股": "美股指数"
} as const

type ContractStockField = typeof SHARED_STOCK_FIELDS[number]
type MissingContractField = Exclude<keyof WatchlistStock, ContractStockField>
type UnknownContractField = Exclude<ContractStockField, keyof WatchlistStock>
type AssertNever<T extends never> = T

// WatchlistStock 新增或删除持久化字段时，这两行会让 H5 的 TypeScript 构建失败。
export type AssertNoMissingStockFields = AssertNever<MissingContractField>
export type AssertNoUnknownStockFields = AssertNever<UnknownContractField>
